const KEYS_SCENES = {
    BATTLE: "BATTLE",
};

const KEYS_ASSETS_SPRITES = {
    MISC_DICE: "MISC_DICE",
    MISC_CARD: "MISC_CARD",
    MISC_DICE_SLOT: "MISC_DICE_SLOT",
    DICE_SLOT: "DICE_SLOT",

    DICE_TYPE_D4: "DICE_TYPE_D4",
    DICE_TYPE_D6: "DICE_TYPE_D6",
    DICE_TYPE_D8: "DICE_TYPE_D8",
    DICE_TYPE_D10: "DICE_TYPE_D10",
    DICE_TYPE_D12: "DICE_TYPE_D12",
    DICE_TYPE_D20: "DICE_TYPE_D20",

    EMOTION_ANGER_ICON: "EMOTION_ANGER_ICON",
    EMOTION_CALM_ICON: "EMOTION_CALM_ICON",
    EMOTION_HAPPINESS_ICON: "EMOTION_HAPPINESS_ICON",
    EMOTION_SADNESS_ICON: "EMOTION_SADNESS_ICON",
    EMOTION_ECSTASY_ICON: "EMOTION_ECSTASY_ICON",
    EMOTION_CONCERN_ICON: "EMOTION_CONCERN_ICON",
    EMOTION_FEAR_ICON: "EMOTION_FEAR_ICON",
    EMOTION_CONFIDENCE_ICON: "EMOTION_CONFIDENCE_ICON",
};

const CONSTANTS_SPRITES_MEASURES = {
    MISC_DICE_SLOT: {
        WIDTH: 64,
        HEIGHT: 64,
        SLICE_TOP: 16,
        SLICE_BOTTOM: 16,
        SLICE_LEFT: 16,
        SLICE_RIGHT: 16
    },
    DICE_SLOT: {
        WIDTH: 154,
        HEIGHT: 153,
        LINE_BORDER: 10
    },
};

export { KEYS_SCENES, KEYS_ASSETS_SPRITES, CONSTANTS_SPRITES_MEASURES };