const KEYS_SCENES = {
    LOAD: "LOAD",
    BATTLE: "BATTLE",
    MAIN_MENU: "MAIN_MENU",
    END: "END",
};

const KEYS_ASSETS_SPRITES = {
    MISC_DICE: "MISC_DICE",
    MISC_CARD: "MISC_CARD",
    MISC_DICE_SLOT: "MISC_DICE_SLOT",
    DICE_SLOT: "DICE_SLOT",
    PAST_CARD: "PAST_CARD",
    FUTURE_CARD: "FUTURE_CARD",
    CARD_HAND_PANEL: "CARD_HAND_PANEL",
    CARD_SELECTION_FRAME: "CARD_SELECTION_FRAME",
    CARD_ATTACK_ACTION: "CARD_ATTACK_ACTION",
    CARD_DEFENCE_ACTION: "CARD_DEFENCE_ACTION",
    CARD_HEAL_ACTION: "CARD_HEAL_ACTION",
    CARD_ACTION_SELECTION_FRAME: "CARD_ACTION_SELECTION_FRAME",
    CARD_ATLAS: "CARD_ATLAS",

    BATTLE_SCENE_BACKGROUND: "BATTLE_SCENE_BACKGROUND",

    DICE_TYPE_D4: "DICE_TYPE_D4",
    DICE_TYPE_D6: "DICE_TYPE_D6",
    DICE_TYPE_D8: "DICE_TYPE_D8",
    DICE_TYPE_D10: "DICE_TYPE_D10",
    DICE_TYPE_D12: "DICE_TYPE_D12",
    DICE_TYPE_D20: "DICE_TYPE_D20",
    DICE_BOX: "DICE_BOX",
    DICE_BOX_SELECTION_FRAME: "DICE_BOX_SELECTION_FRAME",
    DICE_BOX_CONTAINER: "DICE_BOX_CONTAINER",

    TURN_EXECUTION_RING_BUTTON_PRESSED: "TURN_EXECUTION_RING_BUTTON_PRESSED",
    TURN_EXECUTION_RING_BUTTON_RELEASE: "TURN_EXECUTION_RING_BUTTON_RELEASE",

    EMOTION_ANGER_ICON: "EMOTION_ANGER_ICON",
    EMOTION_CALM_ICON: "EMOTION_CALM_ICON",
    EMOTION_HAPPINESS_ICON: "EMOTION_HAPPINESS_ICON",
    EMOTION_SADNESS_ICON: "EMOTION_SADNESS_ICON",
    EMOTION_ECSTASY_ICON: "EMOTION_ECSTASY_ICON",
    EMOTION_CONCERN_ICON: "EMOTION_CONCERN_ICON",
    EMOTION_FEAR_ICON: "EMOTION_FEAR_ICON",
    EMOTION_CONFIDENCE_ICON: "EMOTION_CONFIDENCE_ICON",
};

const KEYS_FONT_FAMILIES = {
    Bauhaus93: "Bauhaus93",
}

const KEYS_SHADER_PIPELINES = {
    rexcrtpipelineplugin : "rexcrtpipelineplugin",
    rextoonifypipelineplugin : "rextoonifypipelineplugin",
};

const KEYS_EVENTS = {
    PLAYER_HEALTH_SET: "PLAYER_HEALTH_SET",
    PLAYER_BLOCK_SET: "PLAYER_BLOCK_SET",
    CURRENT_ENEMIES_ALL_DEFEATED: "CURRENT_ENEMIES_ALL_DEFEATED",
};

const CONSTANTS_SPRITES_MEASURES = {
    MISC_DICE_SLOT: {
        WIDTH: 64,
        HEIGHT: 64,
        SLICE_TOP: 16,
        SLICE_BOTTOM: 16,
        SLICE_LEFT: 16,
        SLICE_RIGHT: 16
    },
    DICE_SLOT: {
        WIDTH: 154,
        HEIGHT: 153,
        LINE_BORDER: 10
    },
    SCENE_CARD: {
        WIDTH: 344,
        HEIGHT: 460,
    },
    SCENE_DICE: {
        WIDTH: 154,
        HEIGHT: 153,
    },
};

const CARD_NAMES = {
    SABER: "Sable", 
    CLUB: "Porra", 
    ARCO: "Arco", 
    CANON: "Cañón", 
    FIRE_SABER: "Sable Igneo", 
    SICKLE: "Hoz de Grangero", 
    KHOPESH: "Khopesh", 
    SHIELD: "Escudo",
    TOTEM: "Tótem",
    SACRED_HORN: "Cuerno Sagrado",
    VITAL_POTION: "Potción Vital",
    LAZZER: "Lázzer",
    TESLA_TOWER: "Tesla (himself)",
    LIGHTSABER: "Sable Lázzer",
    BLOWGUN: "Cerbatana Telescópica",
    RADIATION: "Radiación a Domicilio",
    FORCE_SHIELD: "Campo de Fuerza",
    MEDICAL_KIT: "Botiquín Médico", 
};

export { KEYS_SCENES, KEYS_ASSETS_SPRITES, KEYS_FONT_FAMILIES, KEYS_EVENTS, KEYS_SHADER_PIPELINES, CONSTANTS_SPRITES_MEASURES, CARD_NAMES };